Added design time support for ViewComponent TagHelpers
aspnet/RazorTooling pull request #98
Opened 2016-09-21 17:30 UTC by ajaybhargavb

Issue - aspnet/Mvc#1051

Related PR: https://github.com/aspnet/Mvc/pull/5304

@NTaylorMullen @pranavkm

2016-09-22 03:23 UTC, ajaybhargavb commented
🆙 📅

2016-09-22 16:34 UTC, pranavkm commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +                _populateMethod.Invoke(_serviceCollectionProviderClassInstance, new object[] { serviceCollection, assemblyName });
Does this happen more than once in the lifetime of the process?

2016-09-22 16:42 UTC, pranavkm commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +                var assembly = Assembly.Load(new AssemblyName("Microsoft.AspNetCore.Mvc"));
```c#
var type = Type.GetType("Microsoft.AspNetCore.Mvc.DesignTimeMvcServiceCollectionProvider, Microsoft.AspNetCore.Mvc");

if (type != null)
{
   ...
}
```

2016-09-22 16:42 UTC, pranavkm commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +                var assembly = Assembly.Load(new AssemblyName("Microsoft.AspNetCore.Mvc"));
Also const strings

2016-09-22 16:43 UTC, pranavkm commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +            if (_hasMvcAssembly)
Can we check if `_populateMethod` is not null instead of having a separate variable?

2016-09-22 16:50 UTC, pranavkm commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +                _populateMethod = providerClass.GetMethod(
Can we do something similar to this - https://github.com/aspnet/HttpAbstractions/blob/e3207557342f514deea4618f595a049bfbd7a024/src/Microsoft.AspNetCore.Http.Extensions/HeaderDictionaryTypeExtensions.cs#L223-L234 - to ensure we're getting the right overload of `PopulateServiceCollection`

2016-09-22 16:51 UTC, pranavkm requested changes

2016-09-22 17:07 UTC, NTaylorMullen commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +            : this(tagHelperTypeResolver: new TagHelperTypeResolver())
no need for named params

2016-09-22 17:09 UTC, NTaylorMullen commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +                var serviceCollection = new ServiceCollection();
We need to talk to @Eilon about having DI in RazorTooling.

2016-09-22 17:10 UTC, NTaylorMullen commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +                var directiveDescriptors = new TagHelperDirectiveDescriptor[]
new[]

2016-09-22 17:14 UTC, NTaylorMullen commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +            if (!_loadedAssembly)
Does this ever get hit more than once?

2016-09-22 17:16 UTC, NTaylorMullen commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +                var directiveDescriptors = new TagHelperDirectiveDescriptor[]
You could share the logic from here on down with the falling back to manually resolving descriptors.

Aka, if MVC isn't in the project:

```C#
TagHelperDescriptorResolver tagHelperDescriptorResolver;
if (_hasMvcAssembly)
{
     // Do work to get tagHelperDescriptorResolver from MVC
}
else
{
    tagHelperDescriptorResolver = new TagHelperDescriptorResolver(_tagHelperTypeResolver, _tagHelperDescriptorFactory);
}

// Build resolution context and resolve
// Win
```

2016-09-22 17:26 UTC, NTaylorMullen commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +                _populateMethod = providerClass.GetMethod(
Really sad that we can't just call into `AddMvc` 😢 .

2016-09-22 17:27 UTC, NTaylorMullen reviewed
⌚

2016-09-22 17:32 UTC, NTaylorMullen reviewed
BUgz

2016-09-22 23:00 UTC, ajaybhargavb commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +            if (!_loadedAssembly)
Yes. The `Resolve` method is called every time you resolve an assembly. https://github.com/aspnet/RazorTooling/blob/dev/src/Microsoft.AspNetCore.Razor.Design/ResolveTagHelpersRunCommand.cs#L42

2016-09-22 23:02 UTC, ajaybhargavb commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +                _populateMethod.Invoke(_serviceCollectionProviderClassInstance, new object[] { serviceCollection, assemblyName });
This runs for every assembly that we resolve descriptors from.
Example, in the following command, it runs twice.
 `dotnet razor-tooling resolve-taghelpers .\project.json ViewComponentTagHelper.Web Microsoft.AspNetCore.Mvc.TagHelpers`

2016-09-22 23:43 UTC, ajaybhargavb commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +            if (_hasMvcAssembly)
We could do that but I feel the code looks more readable this way.

2016-09-22 23:56 UTC, ajaybhargavb commented
🆙 📅 Really sucks that Github doesn't hide outdated comments.

2016-09-23 00:05 UTC, NTaylorMullen commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +            const string typeName = "DesignTimeMvcServiceCollectionProvider";
`fullTypeName`; can combine this with the above.

2016-09-23 00:06 UTC, NTaylorMullen approved these changes
Looks good. :shipit:

2016-09-23 18:23 UTC, Eilon commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +                var serviceCollection = new ServiceCollection();
I think we decided this is fine.

2016-09-23 18:55 UTC, ajaybhargavb commented
🆙 📅

2016-09-23 19:00 UTC, pranavkm commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +            if (!_loadedAssembly)
In which case, could we create a delegate from `populateMethod` (https://docs.microsoft.com/en-us/dotnet/core/api/system.reflection.methodinfo#System_Reflection_MethodInfo_CreateDelegate_System_Type_)

2016-09-23 19:01 UTC, pranavkm commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +            _loadedAssembly = true;
Set this after you've loaded the assembly.

2016-09-23 19:01 UTC, pranavkm commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +                var providerClass = Type.GetType($"{typeFullName}, {assemblyName}", throwOnError: true);
Why throwOnError? It returns a `null` if it can't find it by default.

2016-09-23 19:02 UTC, pranavkm commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +                            && methodInfo.ReturnParameter.ParameterType.Equals(typeof(void)))
Probably don't need to check for return type since overloads can only vary by parameters.

2016-09-23 19:03 UTC, pranavkm commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +                _hasMvcAssembly = true;
Couldn't we use the existence of the method to know if Mvc is present?

2016-09-23 19:04 UTC, pranavkm commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +            const string typeFullName = "Microsoft.AspNetCore.Mvc.DesignTimeMvcServiceCollectionProvider";
private const string ... at the top of the class.

2016-09-23 19:05 UTC, pranavkm commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +                                && methodParams[0].ParameterType.Equals(typeof(IServiceCollection))
`&&` on the previous line.

2016-09-23 19:05 UTC, pranavkm commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyViewComponentTagHelperDescriptorResolver.cs
> +        //private Type _serviceCollectionExtensionsClass;
?

2016-09-23 19:06 UTC, pranavkm commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyViewComponentTagHelperDescriptorResolver.cs
> +﻿// Copyright (c) .NET Foundation. All rights reserved.
Do you still need this type?

2016-09-23 19:07 UTC, pranavkm requested changes

2016-09-23 19:08 UTC, ajaybhargavb commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyViewComponentTagHelperDescriptorResolver.cs
> +﻿// Copyright (c) .NET Foundation. All rights reserved.
Accidental check-in. Removed.

2016-09-23 22:07 UTC, pranavkm commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +                var providerClass = Type.GetType($"{TypeFullName}, {MvcAssemblyName}", throwOnError: true);
`throwOnError: false`

2016-09-23 22:07 UTC, ajaybhargavb commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +                var providerClass = Type.GetType($"{TypeFullName}, {MvcAssemblyName}", throwOnError: true);
Sorry didn't fully update yet

2016-09-23 22:14 UTC, pranavkm commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +            _populateMethod = providerClass.GetMethods(BindingFlags.Public | BindingFlags.Static)
```
var populateMethod = ...;
_populateMethodDelegate = populateMethod.CreateDelegate(typeof(Action<IServiceCollection, string>));
```

2016-09-23 22:16 UTC, pranavkm commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +            if (!_isInitialized)
We could move the if check in to the method. I really couldn't find a suitable example in AspNetCore so something from the old world (https://github.com/aspnet/AspNetWebStack/blob/1a987f82d648a95aabed7d35e4c2bee17185c44d/src/System.Web.Http/Routing/RouteCollectionRoute.cs#L41)

2016-09-23 22:16 UTC, pranavkm requested changes
Almost there 👍

2016-09-23 23:26 UTC, ajaybhargavb commented
🆙 📅

2016-09-23 23:31 UTC, pranavkm commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +                _populateMethodDelegate.DynamicInvoke(serviceCollection, assemblyName);
`_populateMethodDelegate(serviceCollection, assemblyName);`

2016-09-23 23:31 UTC, pranavkm approved these changes
:shipit:

2016-09-23 23:32 UTC, pranavkm commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +        private Delegate _populateMethodDelegate;
`private Action<IServiceCollection, string> _populateMethodDelegate;`

2016-09-23 23:32 UTC, pranavkm commented on src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs
> +            _populateMethodDelegate = populateMethod?.CreateDelegate(typeof(Action<IServiceCollection, string>));
You'd have to cast here.

2016-09-23 23:32 UTC, pranavkm approved these changes
:shipit: x2

2016-09-24 00:54 UTC, merged